### ISSUE TITLE
add hover class when dragover

### ISSUE THREAD

**Issue by aytacworld** [fvilers/angular-file-dropzone#3]
I'm using this plugin, but I can't add my own hover class, because you are doing event.stopPropagation on dragover and dragstart, so I cloned your project and updated the directive.
How can I do a pull request?

**Comment by fvilers** [comment]
Hi Adem, sorry for the late answer. You can easily add an hovering class with the current version. Here's how:

```
<div ngFileDropzone (fileDrop)="addFile($event)" [ngClass]="{'hover': hovering }" (dragenter)="hovering = true" (dragleave)="hovering = false" (drop)="hovering = false"></div>
```

**Comment by aytacworld** [comment]
Yes I can use this, thank you
