### ISSUE TITLE
Add File or Blob representation to DroppedFile interface

### ISSUE THREAD

**Issue by jongunter** [fvilers/angular-file-dropzone#5]
It would be nice to have the file represented as a `File` or `Blob` object in `DroppedFile`. Maybe even a method such as `DroppedFile.prototype.getBlob()` if that preserves resources.

**Comment by jongunter** [comment]
Here's what I used to do the conversion-- maybe build it into the library: 
```
 // based on https://stackoverflow.com/questions/4998908/convert-data-uri-to-file-then-append-to-formdata
  createFileFromDroppedFile(file: DroppedFile): File {
    const dataURI = file.dataURL;
    const name = file.name
    const urlSegments = dataURI.split(',');
    const mimeType = dataURI.split(',')[0].split(':')[1].split(';')[0];
    const binary = atob(urlSegments[1]);
    const array = [];
    for(let i = 0; i < binary.length; i++) {
      array.push(binary.charCodeAt(i));
    }
    return new File([new Uint8Array(array)], name , {type: mimeType});
  }
```

**Comment by fvilers** [comment]
Thanks for the suggestion, I added a readMode so that you can choose how the file should be read.

**Comment by jongunter** [comment]
Wow...fast response and just what I needed. Thank you so much!

Turns out my `createFileFromDroppedFile` method hack worked fine for most use cases, but crashed the browser with large files.

**Comment by fvilers** [comment]
Hi @jongunter, thanks! I try to work on these hobby project when I have some time. I will do some tests with large files on my side too, just in case.
